services:
  - type: web
    name: nakamal-backend-api
    runtime: node
    rootDir: backend-api
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commit
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nakamal-db
          property: connectionString
      - key: DATABASE_SSL
        value: "false"
      - key: AUTO_RUN_MIGRATIONS
        value: "true"

  - type: web
    name: nakamal-frontend-static
    runtime: static
    rootDir: frontend-static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: FRONTEND_API_BASE_URL
        sync: false

databases:
  - name: nakamal-db
    plan: free
    databaseName: nakamal_app
